export const FLOWER_SVGS = [
  "forgetmenot-earth.svg",
  "forgetmenot-forest.svg",
  "forgetmenot-ocean.svg",
  "forgetmenot-pastel.svg",
  "forgetmenot-sunset.svg",
  "lily-earth.svg",
  "lily-forest.svg",
  "lily-ocean.svg",
  "lily-pastel.svg",
  "lily-sunset.svg",
  "peony-earth.svg",
  "peony-forest.svg",
  "peony-ocean.svg",
  "peony-pastel.svg",
  "peony-sunset.svg",
  "rose-earth.svg",
  "rose-forest.svg",
  "rose-ocean.svg",
  "rose-pastel.svg",
  "rose-sunset.svg",
  "sunflower-pastel.svg",
  "tulip-earth.svg",
  "tulip-forest.svg",
  "tulip-ocean.svg",
  "tulip-pastel.svg",
  "tulip-sunset.svg",
] as const;
